/**
 * ============================================================================
 * IRON STRIKE TRADING - EMAIL TEMPLATES
 * ============================================================================
 * 
 * Professional HTML email templates for all notification types.
 * Templates are responsive and work across major email clients.
 * 
 * ============================================================================
 */

const BRAND_COLORS = {
  primary: "#10b981",
  primaryDark: "#059669",
  background: "#0a0f0d",
  cardBg: "#111827",
  text: "#f9fafb",
  textMuted: "#9ca3af",
  border: "#1f2937",
  success: "#22c55e",
  warning: "#f59e0b",
  danger: "#ef4444",
};

const baseTemplate = (content: string, preheader?: string): string => `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Iron Strike Trading</title>
  ${preheader ? `<span style="display:none;font-size:1px;color:#333;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">${preheader}</span>` : ""}
  <style>
    @media only screen and (max-width: 600px) {
      .container { width: 100% !important; padding: 16px !important; }
      .content { padding: 24px !important; }
      .signal-box { padding: 16px !important; }
    }
  </style>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: ${BRAND_COLORS.background}; color: ${BRAND_COLORS.text};">
  <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color: ${BRAND_COLORS.background};">
    <tr>
      <td style="padding: 40px 20px;">
        <table class="container" role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" style="margin: 0 auto; max-width: 600px;">
          <!-- Header -->
          <tr>
            <td style="padding-bottom: 24px; text-align: center;">
              <img src="https://ironstriketrading.com/logo.png" alt="Iron Strike Trading" width="180" style="max-width: 180px; height: auto;" />
            </td>
          </tr>
          <!-- Content -->
          <tr>
            <td class="content" style="background-color: ${BRAND_COLORS.cardBg}; border-radius: 12px; padding: 32px; border: 1px solid ${BRAND_COLORS.border};">
              ${content}
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding-top: 24px; text-align: center;">
              <p style="margin: 0 0 8px 0; font-size: 12px; color: ${BRAND_COLORS.textMuted};">
                Iron Strike Trading - AI-Powered Options Intelligence
              </p>
              <p style="margin: 0 0 16px 0; font-size: 12px; color: ${BRAND_COLORS.textMuted};">
                <a href="https://ironstriketrading.com" style="color: ${BRAND_COLORS.primary}; text-decoration: none;">Website</a> &nbsp;|&nbsp;
                <a href="https://ironstriketrading.com/contact" style="color: ${BRAND_COLORS.primary}; text-decoration: none;">Contact</a> &nbsp;|&nbsp;
                <a href="https://ironstriketrading.com/privacy" style="color: ${BRAND_COLORS.primary}; text-decoration: none;">Privacy</a>
              </p>
              <p style="margin: 0; font-size: 11px; color: ${BRAND_COLORS.textMuted};">
                This email was sent by Iron Strike Trading. Options trading involves substantial risk.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
`;

export interface SignalAlertData {
  symbol: string;
  action: string;
  strike: number;
  expiration: string;
  confidence: number;
  premium?: number;
  entryPrice?: number;
  stopLoss?: number;
  takeProfit?: number;
  rationale?: string;
}

export function signalAlertTemplate(data: SignalAlertData): { html: string; text: string } {
  const actionColor = data.action.includes("CALL") ? BRAND_COLORS.success : BRAND_COLORS.danger;
  
  const html = baseTemplate(`
    <h1 style="margin: 0 0 8px 0; font-size: 24px; color: ${BRAND_COLORS.primary};">
      Trading Signal Alert
    </h1>
    <p style="margin: 0 0 24px 0; font-size: 14px; color: ${BRAND_COLORS.textMuted};">
      New options signal generated by Iron Strike AI
    </p>
    
    <div class="signal-box" style="background-color: ${BRAND_COLORS.background}; border-radius: 8px; padding: 24px; margin-bottom: 24px; border-left: 4px solid ${actionColor};">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;">
        <span style="font-size: 28px; font-weight: bold; color: ${BRAND_COLORS.text};">${data.symbol}</span>
        <span style="background-color: ${actionColor}; color: white; padding: 6px 12px; border-radius: 6px; font-weight: bold; font-size: 14px;">
          ${data.action}
        </span>
      </div>
      
      <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border};">
            <span style="color: ${BRAND_COLORS.textMuted};">Strike Price</span>
          </td>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border}; text-align: right; font-weight: bold;">
            $${data.strike.toFixed(2)}
          </td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border};">
            <span style="color: ${BRAND_COLORS.textMuted};">Expiration</span>
          </td>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border}; text-align: right; font-weight: bold;">
            ${data.expiration}
          </td>
        </tr>
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border};">
            <span style="color: ${BRAND_COLORS.textMuted};">Confidence</span>
          </td>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border}; text-align: right; font-weight: bold; color: ${BRAND_COLORS.primary};">
            ${data.confidence}%
          </td>
        </tr>
        ${data.premium ? `
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border};">
            <span style="color: ${BRAND_COLORS.textMuted};">Premium</span>
          </td>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border}; text-align: right; font-weight: bold;">
            $${data.premium.toFixed(2)}
          </td>
        </tr>
        ` : ""}
        ${data.stopLoss ? `
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border};">
            <span style="color: ${BRAND_COLORS.textMuted};">Stop Loss</span>
          </td>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border}; text-align: right; color: ${BRAND_COLORS.danger};">
            $${data.stopLoss.toFixed(2)}
          </td>
        </tr>
        ` : ""}
        ${data.takeProfit ? `
        <tr>
          <td style="padding: 8px 0;">
            <span style="color: ${BRAND_COLORS.textMuted};">Take Profit</span>
          </td>
          <td style="padding: 8px 0; text-align: right; color: ${BRAND_COLORS.success};">
            $${data.takeProfit.toFixed(2)}
          </td>
        </tr>
        ` : ""}
      </table>
    </div>
    
    ${data.rationale ? `
    <div style="margin-bottom: 24px;">
      <h3 style="margin: 0 0 8px 0; font-size: 14px; color: ${BRAND_COLORS.textMuted};">Analysis</h3>
      <p style="margin: 0; font-size: 14px; line-height: 1.6; color: ${BRAND_COLORS.text};">
        ${data.rationale}
      </p>
    </div>
    ` : ""}
    
    <a href="https://ironstriketrading.com/app/live" style="display: block; text-align: center; background-color: ${BRAND_COLORS.primary}; color: white; padding: 14px 24px; border-radius: 8px; text-decoration: none; font-weight: bold;">
      View Signal Details
    </a>
    
    <p style="margin: 24px 0 0 0; font-size: 12px; color: ${BRAND_COLORS.textMuted}; text-align: center;">
      This is an automated alert. Do your own research before trading.
    </p>
  `, `New ${data.action} signal for ${data.symbol} at $${data.strike} strike`);

  const text = `
IRONSTRIKE TRADING SIGNAL ALERT

Symbol: ${data.symbol}
Action: ${data.action}
Strike: $${data.strike.toFixed(2)}
Expiration: ${data.expiration}
Confidence: ${data.confidence}%
${data.premium ? `Premium: $${data.premium.toFixed(2)}` : ""}
${data.stopLoss ? `Stop Loss: $${data.stopLoss.toFixed(2)}` : ""}
${data.takeProfit ? `Take Profit: $${data.takeProfit.toFixed(2)}` : ""}

${data.rationale ? `Analysis: ${data.rationale}` : ""}

View details: https://ironstriketrading.com/app/live

This is an automated alert. Do your own research before trading.
  `.trim();

  return { html, text };
}

export interface TicketConfirmationData {
  ticketNumber: string;
  name?: string;
  subject: string;
  message: string;
  createdAt: Date;
}

export function ticketConfirmationTemplate(data: TicketConfirmationData): { html: string; text: string } {
  const html = baseTemplate(`
    <h1 style="margin: 0 0 8px 0; font-size: 24px; color: ${BRAND_COLORS.primary};">
      Support Ticket Created
    </h1>
    <p style="margin: 0 0 24px 0; font-size: 14px; color: ${BRAND_COLORS.textMuted};">
      Thank you for contacting us. We've received your request.
    </p>
    
    <div style="background-color: ${BRAND_COLORS.background}; border-radius: 8px; padding: 24px; margin-bottom: 24px;">
      <div style="margin-bottom: 16px;">
        <span style="display: inline-block; background-color: ${BRAND_COLORS.primary}; color: white; padding: 6px 12px; border-radius: 6px; font-family: monospace; font-size: 14px;">
          ${data.ticketNumber}
        </span>
      </div>
      
      <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
        ${data.name ? `
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border};">
            <span style="color: ${BRAND_COLORS.textMuted};">Name</span>
          </td>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border}; text-align: right;">
            ${data.name}
          </td>
        </tr>
        ` : ""}
        <tr>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border};">
            <span style="color: ${BRAND_COLORS.textMuted};">Subject</span>
          </td>
          <td style="padding: 8px 0; border-bottom: 1px solid ${BRAND_COLORS.border}; text-align: right;">
            ${data.subject}
          </td>
        </tr>
        <tr>
          <td style="padding: 8px 0;">
            <span style="color: ${BRAND_COLORS.textMuted};">Created</span>
          </td>
          <td style="padding: 8px 0; text-align: right;">
            ${data.createdAt.toLocaleString()}
          </td>
        </tr>
      </table>
    </div>
    
    <div style="margin-bottom: 24px;">
      <h3 style="margin: 0 0 8px 0; font-size: 14px; color: ${BRAND_COLORS.textMuted};">Your Message</h3>
      <div style="background-color: ${BRAND_COLORS.background}; border-radius: 8px; padding: 16px; border-left: 3px solid ${BRAND_COLORS.primary};">
        <p style="margin: 0; font-size: 14px; line-height: 1.6; color: ${BRAND_COLORS.text}; white-space: pre-wrap;">
          ${data.message}
        </p>
      </div>
    </div>
    
    <p style="margin: 0 0 16px 0; font-size: 14px; color: ${BRAND_COLORS.text};">
      Our support team typically responds within 24-48 hours. Please save your ticket number for reference.
    </p>
    
    <p style="margin: 0; font-size: 12px; color: ${BRAND_COLORS.textMuted};">
      Need urgent assistance? Reply to this email or contact us at 
      <a href="mailto:support@ironstriketrading.com" style="color: ${BRAND_COLORS.primary};">support@ironstriketrading.com</a>
    </p>
  `, `Ticket ${data.ticketNumber} - We've received your request`);

  const text = `
SUPPORT TICKET CREATED

Ticket Number: ${data.ticketNumber}
${data.name ? `Name: ${data.name}` : ""}
Subject: ${data.subject}
Created: ${data.createdAt.toLocaleString()}

Your Message:
${data.message}

Our support team typically responds within 24-48 hours.
Please save your ticket number for reference.

Need urgent assistance? Contact support@ironstriketrading.com
  `.trim();

  return { html, text };
}

export interface TransactionalEmailData {
  title: string;
  message: string;
  actionUrl?: string;
  actionText?: string;
  details?: Record<string, string>;
}

export function transactionalTemplate(data: TransactionalEmailData): { html: string; text: string } {
  const html = baseTemplate(`
    <h1 style="margin: 0 0 16px 0; font-size: 24px; color: ${BRAND_COLORS.text};">
      ${data.title}
    </h1>
    
    <p style="margin: 0 0 24px 0; font-size: 15px; line-height: 1.6; color: ${BRAND_COLORS.text};">
      ${data.message}
    </p>
    
    ${data.details ? `
    <div style="background-color: ${BRAND_COLORS.background}; border-radius: 8px; padding: 24px; margin-bottom: 24px;">
      <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
        ${Object.entries(data.details).map(([key, value], index, arr) => `
        <tr>
          <td style="padding: 8px 0; ${index < arr.length - 1 ? `border-bottom: 1px solid ${BRAND_COLORS.border};` : ""}">
            <span style="color: ${BRAND_COLORS.textMuted};">${key}</span>
          </td>
          <td style="padding: 8px 0; ${index < arr.length - 1 ? `border-bottom: 1px solid ${BRAND_COLORS.border};` : ""} text-align: right; font-weight: bold;">
            ${value}
          </td>
        </tr>
        `).join("")}
      </table>
    </div>
    ` : ""}
    
    ${data.actionUrl && data.actionText ? `
    <a href="${data.actionUrl}" style="display: block; text-align: center; background-color: ${BRAND_COLORS.primary}; color: white; padding: 14px 24px; border-radius: 8px; text-decoration: none; font-weight: bold;">
      ${data.actionText}
    </a>
    ` : ""}
  `, data.message.substring(0, 100));

  const text = `
${data.title}

${data.message}

${data.details ? Object.entries(data.details).map(([k, v]) => `${k}: ${v}`).join("\n") : ""}

${data.actionUrl ? `${data.actionText}: ${data.actionUrl}` : ""}
  `.trim();

  return { html, text };
}

export interface MarketingEmailData {
  preheader: string;
  headline: string;
  subheadline?: string;
  heroImageUrl?: string;
  bodyContent: string;
  ctaUrl: string;
  ctaText: string;
  unsubscribeUrl?: string;
}

export function marketingTemplate(data: MarketingEmailData): { html: string; text: string } {
  const html = baseTemplate(`
    ${data.heroImageUrl ? `
    <img src="${data.heroImageUrl}" alt="" style="width: 100%; height: auto; border-radius: 8px; margin-bottom: 24px;" />
    ` : ""}
    
    <h1 style="margin: 0 0 8px 0; font-size: 28px; color: ${BRAND_COLORS.text}; text-align: center;">
      ${data.headline}
    </h1>
    
    ${data.subheadline ? `
    <p style="margin: 0 0 24px 0; font-size: 16px; color: ${BRAND_COLORS.primary}; text-align: center;">
      ${data.subheadline}
    </p>
    ` : ""}
    
    <div style="margin-bottom: 32px; font-size: 15px; line-height: 1.7; color: ${BRAND_COLORS.text};">
      ${data.bodyContent}
    </div>
    
    <a href="${data.ctaUrl}" style="display: block; text-align: center; background-color: ${BRAND_COLORS.primary}; color: white; padding: 16px 32px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px;">
      ${data.ctaText}
    </a>
    
    ${data.unsubscribeUrl ? `
    <p style="margin: 32px 0 0 0; font-size: 11px; color: ${BRAND_COLORS.textMuted}; text-align: center;">
      Don't want to receive these emails? 
      <a href="${data.unsubscribeUrl}" style="color: ${BRAND_COLORS.textMuted}; text-decoration: underline;">Unsubscribe</a>
    </p>
    ` : ""}
  `, data.preheader);

  const text = `
${data.headline}
${data.subheadline || ""}

${data.bodyContent.replace(/<[^>]*>/g, "")}

${data.ctaText}: ${data.ctaUrl}

${data.unsubscribeUrl ? `Unsubscribe: ${data.unsubscribeUrl}` : ""}
  `.trim();

  return { html, text };
}

export interface PriceAlertEmailData {
  symbol: string;
  alertType: "above" | "below";
  targetPrice: number;
  currentPrice: number;
  triggeredAt: Date;
}

export function priceAlertTemplate(data: PriceAlertEmailData): { html: string; text: string } {
  const direction = data.alertType === "above" ? "risen above" : "fallen below";
  const color = data.alertType === "above" ? BRAND_COLORS.success : BRAND_COLORS.danger;

  const html = baseTemplate(`
    <h1 style="margin: 0 0 8px 0; font-size: 24px; color: ${BRAND_COLORS.primary};">
      Price Alert Triggered
    </h1>
    <p style="margin: 0 0 24px 0; font-size: 14px; color: ${BRAND_COLORS.textMuted};">
      Your price alert has been triggered
    </p>
    
    <div style="background-color: ${BRAND_COLORS.background}; border-radius: 8px; padding: 24px; margin-bottom: 24px; text-align: center;">
      <div style="font-size: 36px; font-weight: bold; color: ${BRAND_COLORS.text}; margin-bottom: 8px;">
        ${data.symbol}
      </div>
      <div style="font-size: 14px; color: ${BRAND_COLORS.textMuted}; margin-bottom: 16px;">
        has ${direction} your target
      </div>
      <div style="display: inline-block; background-color: ${color}; color: white; padding: 12px 24px; border-radius: 8px; font-size: 24px; font-weight: bold;">
        $${data.currentPrice.toFixed(2)}
      </div>
      <div style="margin-top: 16px;">
        <span style="color: ${BRAND_COLORS.textMuted};">Target: </span>
        <span style="color: ${BRAND_COLORS.text}; font-weight: bold;">$${data.targetPrice.toFixed(2)}</span>
      </div>
    </div>
    
    <p style="margin: 0 0 16px 0; font-size: 14px; color: ${BRAND_COLORS.textMuted}; text-align: center;">
      Triggered at ${data.triggeredAt.toLocaleString()}
    </p>
    
    <a href="https://ironstriketrading.com/app/alerts" style="display: block; text-align: center; background-color: ${BRAND_COLORS.primary}; color: white; padding: 14px 24px; border-radius: 8px; text-decoration: none; font-weight: bold;">
      Manage Alerts
    </a>
  `, `${data.symbol} has ${direction} $${data.targetPrice.toFixed(2)}`);

  const text = `
PRICE ALERT TRIGGERED

${data.symbol} has ${direction} your target of $${data.targetPrice.toFixed(2)}

Current Price: $${data.currentPrice.toFixed(2)}
Triggered: ${data.triggeredAt.toLocaleString()}

Manage your alerts: https://ironstriketrading.com/app/alerts
  `.trim();

  return { html, text };
}
